#!/bin/sh
#
# Squish a otapackage for distribution
# thanks to cyanogen
#

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
   SED=sed
else
   OUT_TARGET_HOST=darwin-x86
   MD5=md5
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
   SED=gsed
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
	exit 1
fi

if [ ! -f "$OTAPACKAGE" ]; then
	echo "$OTAPACKAGE doesn't exist!";
	exit 1
fi

OPTICHARGER=$ANDROID_BUILD_TOP/vendor/motorola/common/tools/opticharger
QUIET=-q
DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"

REPACK=$OUT/repack.d
printf "Sanitizing environment..."
rm -rf $REPACK
mkdir -p $REPACK
echo


# Unpack the otapackage and opticharge all apks
mkdir $REPACK/ota
(
cd $REPACK/ota
printf "Unpacking $OTAPACKAGE..."
unzip $QUIET $OTAPACKAGE
echo

# Move all apks to the same directory so xargs can
# use also with framework-res.apk. This allow process
# framework-res.apk in parallel with other apks
mkdir -p $REPACK/parallel
cd $REPACK/parallel
cp $REPACK/ota/system/framework/framework-res.apk .
cp $REPACK/ota/system/app/*.apk .

# Do optimization in parallel
find ./ -name \*.apk | $XARGS $OPTICHARGER

# Move optimized apks to repack directory
mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/

# Return to directory
cd $REPACK/ota
rm -rf $REPACK/parallel
)

# Remove unwanted Apps
rm $REPACK/ota/system/app/RomManager.apk 2> /dev/null

# Fix build.prop
$SED -i \
	-e '/ro\.kernel\.android\.checkjni/d' \
	-e '/ro\.build\.type/s/eng/user/' \
	$REPACK/ota/system/build.prop


# Delete unnecessary binaries
( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )

# No need for recovery
rm -rf $REPACK/ota/recovery

# Strip modules
[ -d $REPACK/ota/system/lib/modules ] && \
	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded

# move gralloc to where it will be recognized and camera out of the way for now in kexec builds
if [ "$TARGET_PRODUCT" = "solana" ]; then
cp -f $REPACK/ota/system/vendor/lib/hw/gralloc.omap4430.so $REPACK/ota/system/vendor/lib/hw/gralloc.omap4.so
mv $REPACK/ota/system/lib/hw/camera.omap4.so $REPACK/ota/system/lib/hw/camera.omap4.so.bak
fi

if [ -f $ANDROID_BUILD_TOP/vendor/nos/killrom/README.md ];
then
rm $REPACK/ota/system/app/Gallery.apk
rm $REPACK/ota/system/addon.d/50-backup.sh
rm $REPACK/ota/system/bin/backuptool.sh
rm $REPACK/ota/system/bin/backuptool.functions
rm $REPACK/ota/system/bin/blacklist
fi

# Determine what to name the new signed package
REALDATE=`date -u +%Y%m%d`

if [ -f $ANDROID_BUILD_TOP/vendor/cm/LICENSE ];
then
MODVERSION=`sed -n -e'/ro\.cm\.version/s/^.*=//p' $REPACK/ota/system/build.prop`
OUTFILE=$OUT/cm-$MODVERSION.zip
OTANAME=cm-10
echo MODVERSION: $MODVERSION
elif [ -f $ANDROID_BUILD_TOP/vendor/aokp/vendorsetup.sh ];
then
VERSION=`sed -n -e'/ro.aokp.version/s/^.*=//p' $REPACK/ota/system/build.prop`
MODVERSION="$VERSION"
OUTFILE=$OUT/JB-$MODVERSION.zip
OTANAME=JB-$TARGET_PRODUCT\_unofficial
elif [ -f $ANDROID_BUILD_TOP/vendor/cna/vendorsetup.sh ];
then
MODVERSION=`sed -n -e'/ro\.modversion/s/^.*Codename-Android-//p' $REPACK/ota/system/build.prop`
OUTFILE=$OUT/JB-$TARGET_PRODUCT-$REALDATE.zip
OTANAME=JB-$TARGET_PRODUCT
echo MODVERSION: $MODVERSION
else
OUTFILE=$OUT/JB-$TARGET_PRODUCT-$REALDATE.zip
OTANAME=JB-$TARGET_PRODUCT
fi

# Pack it up and sign
printf "Zipping package..."
( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
echo
printf "Signing package..."
SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx1536m \
	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
	$REPACK/update.zip $OUTFILE
echo
printf "Cleaning up..."
rm -rf $REPACK
echo

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
$MD5 $img >$img.md5sum
echo
echo $CL_GRN"Package complete: $OUTFILE"$CL_RST
cat $img.md5sum
echo
)

exit 0
