#!/bin/bash
#
# Squish an otapackage for distribution
# thanks to cyanogen
#

. $ANDROID_BUILD_TOP/vendor/motorola/common/tools/functions

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
   SED=sed
else
   OUT_TARGET_HOST=darwin-x86
   MD5=md5
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
   SED=gsed
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
	exit 1
fi

if [ ! -f "$OTAPACKAGE" ]; then
	echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
	exit 1
fi

# Strip modules
[ -d $REPACK/ota/system/lib/modules ] && \
	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded

# move gralloc to where it will be recognized and camera out of the way for now in kexec builds
if [ "$TARGET_PRODUCT" = "solana" ]; then
cp -f $OUTsystem/vendor/lib/hw/gralloc.omap4430.so $OUT/system/vendor/lib/hw/gralloc.omap4.so
mv $OUT/system/lib/hw/camera.omap4.so $OUT/system/lib/hw/camera.omap4.so.bak
fi

if [ -f $ANDROID_BUILD_TOP/vendor/nos/killrom/README.md ];
then
rm $OUT/system/app/Gallery.apk
rm $OUT/system/addon.d/50-backup.sh
rm $OUT/system/bin/backuptool.sh
rm $OUT/system/bin/backuptool.functions
rm $OUT/system/bin/blacklist
fi

# Determine what to name the new package
REALDATE=`date -u +%Y%m%d`

if [ -f $ANDROID_BUILD_TOP/vendor/cm/LICENSE ];
then
MODVERSION=`sed -n -e'/ro\.cm\.version/s/^.*=//p' $OUT/system/build.prop`
echo -e $CL_CYN"MODVERSION: $MODVERSION"$CL_RST
OUTFILE=$OUT/cm-$MODVERSION.zip
elif [ -f $ANDROID_BUILD_TOP/vendor/aokp/vendorsetup.sh ];
then
VERSION=`sed -n -e'/ro.aokp.version/s/^.*=//p' $OUT/system/build.prop`
MODVERSION="$VERSION"
echo -e $CL_CYN"MODVERSION: $MODVERSION"$CL_RST
OUTFILE=$OUT/JB-$MODVERSION.zip
elif [ -f $ANDROID_BUILD_TOP/vendor/cna/vendorsetup.sh ];
then
MODVERSION=`sed -n -e'/ro\.modversion/s/^.*Codename-Android-//p' $OUT/system/build.prop`
OUTFILE=$OUT/JB-$TARGET_PRODUCT-$REALDATE.zip
echo -e $CL_CYN"MODVERSION: $MODVERSION"$CL_RST
else
OUTFILE=$OUT/JB-$TARGET_PRODUCT-$REALDATE.zip
fi

ln -f $OTAPACKAGE $OUTFILE

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
$MD5 $img >$img.md5sum
echo
echo -e $CL_GRN"Package complete: $OUTFILE"$CL_RST
echo -e $CL_GRN"md5: $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
echo
)

exit 0
